Models/Employee.cs
using System.ComponentModel.DataAnnotations;
using System.IO.Compression;

namespace EmployeeRegistrationApp.Models
{
    public class Employee
    {
        [Required]
        [StringLength(50, ErrorMessage ="Employee Id is required")]
        public string EmployeeId { get; set; } = string.Empty;

        [Required]
        [RegularExpression(@"^[a-zA-Z\s]+$",ErrorMessage = "Name can only contain letters & spaces.")]
        //ensures that only alpha. chars.(both upper and lower case) and space are allowed.
        //limits the length of name to 50 characters
        public string Name { get; set; } = String.Empty;

        [Required]
        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-za-z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "Invalid Email format")]
        //ensures that input email and vaild email structures only are allowed.
        public string Email { get; set; } = String.Empty;

        [Required(ErrorMessage = "Department is required")]
        public string Department{ get; set; } = String.Empty;

        [Required(ErrorMessage = "Position is required")]
        public string Position { get; set;} = String.Empty;

        [Required(ErrorMessage = "WorkLocation  is required")]
        public string WorkLocation { get; set; } = String.Empty;

        [Required(ErrorMessage = "Status  is required")]
        public string Status { get; set; } = String.Empty;
    }
}

Models/ErrorViewModel.cs
namespace EmployeeRegistrationApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using EmployeeRegistrationApp.Models;
using Microsoft.EntityFrameworkCore;

namespace EmployeeRegistrationApp.Controllers
{
    public class EmployeeController : Controller
    {
 
        public IActionResult Register()
        {   
            var employee = new Employee();
            return View(employee);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(Employee employee)
        {
            if (ModelState.IsValid) 
            {
                //Save employee data to database
                return View("Acknowledgement", employee);
            }
            return View(employee); //Return the model in case of errors or Data Validation fails
        }          
    }
}

Controllers/HomeController.cs
using EmployeeRegistrationApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmployeeRegistrationApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Employee/Acknowledgement.cshtml
@model EmployeeRegistrationApp.Models.Employee

<h1>Registration Successful!</h1>
<p>Thankyou, @Model.Name, for registrating with the @Model.Department department.</p>
<p>EmployeeId:@Model.EmployeeId</p>
<p>Name:@Model.Name</p>
<p>Email:@Model.Email</p>
<p>Department:@Model.Department</p>
<p>Position:@Model.Position</p>
<p>Work Location:@Model.WorkLocation</p>
<p>Status:@Model.Status</p>
<a href="@Url.Action("Register", "Employee")" class=" btn btn-primary">Register Another Employee</a>

Views/Employee/Register.cshtml
@model EmployeeRegistrationApp.Models.Employee
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h2>Employee Registration</h2>

    <form asp-controller="Employee" asp-action="Register" method="post">
    <div class="form-group">
        <label asp-for="EmployeeId"></label>
        <input asp-for="EmployeeId" class="form-control" placeholder="EmployeeID" />
        <span asp-validation-for="EmployeeId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" placeholder="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" placeholder="Email" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Department"></label>
        <select name="Department" class="form-control">
            <option value="" disabled selected>-- Select Department--</option>
            <option value="QA">QA</option>
            <option value="IT">IT</option>
            <option value="Finance">Finance</option>
            <option value="Admin">Admin</option>
            <span asp-validation-for="Department" class="text-danger"></span>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Position"></label>
        <select name="Position" class="form-control">
        <option value=""disabled selected>-- Select Position--</option>
        <option value="Developer">Developer</option>
        <option value="Tester">Tester</option>
        <option value="Teamlead">Teamlead</option>
        <option value="Manager">Manager</option>
        <span asp-validation-for="Position" class="text-danger"></span>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="WorkLocation"></label>
        <select name="WorkLocation" class="form-control">
            <option value="" disabled selected>-- Select WorkLocation--</option>
            <option value="HDC">HDC</option>
            <option value="BDC">BDC</option>
            <option value="KDC">KDC</option>
            <option value="MDC">MDC</option>
            <span asp-validation-for="WorkLocation" class="text-danger"></span>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Status"></label>
        <select name="Status" class="form-control">
            <option value="" disabled selected>-- Select Status-</option>
            <option value="Active">Active</option>
            <option value="InActive">InActive</option>
            <span asp-validation-for="Status" class="text-danger"></span>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
    

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Employee Registration</h1>
    <p>Click below to register a new employee.</p>
    <a class="btn btn-primary btn-lg" asp-controller="Employee" asp-action="Register">Register</a>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - Employee Registration App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdeliver.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/EmployeeRegistrationApp.styles.css" asp-append-version="true" />
</head>
<body>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobrastive/3.2.12/jquery.validate.unobrastive.min.js"></script>
    <script src="https://cdn.jsdeliver.net/npm/bootstrap@Html5.1.3/dist/js/bootstrap.bundle.min.js"></script>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="wrapper-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Register">EmployeeRegistrationApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-buttom footer text-muted">
        <div class="container">
            &copy; 2024 - EmployeeRegistrationApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>